# Generated by Django 3.0 on 2019-12-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('squirrel_id', models.CharField(help_text='Gives Unique Squirrel ID. Sighting added only if the ID does not already exist', max_length=20, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(help_text='Gives the Latitude of Sighting')),
                ('longitude', models.FloatField(help_text='Gives the Longitude of Sighting')),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Gives the time of sighting occurence - AM or PM', max_length=2)),
                ('date', models.IntegerField(help_text='Gives the date of sighting in YYYY-MM-DD format')),
                ('age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('', '')], default='Adult', help_text='Age of Squirrel - Adult or Juvenile', max_length=10, null=True)),
                ('fur_color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('', '')], default='Gray', help_text='Gives Fur color of the Squirrel', max_length=20, null=True)),
                ('location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), ('', '')], default='Ground Plane', help_text='Location of Squirrel - on ground plane or above ground plane', max_length=30, null=True)),
                ('specific_location', models.CharField(blank=True, help_text='Additional information on Specific location of the Squirrel', max_length=200, null=True)),
                ('running', models.BooleanField(default=False)),
                ('chasing', models.BooleanField(default=False)),
                ('climbing', models.BooleanField(default=False)),
                ('eating', models.BooleanField(default=False)),
                ('foraging', models.BooleanField(default=False)),
                ('other_activities', models.CharField(blank=True, help_text='Other Activity', max_length=200, null=True)),
                ('kuks', models.BooleanField(default=False)),
                ('quaas', models.BooleanField(default=False)),
                ('moans', models.BooleanField(default=False)),
                ('tail_flags', models.BooleanField(default=False)),
                ('tail_twitches', models.BooleanField(default=False)),
                ('approaches', models.BooleanField(default=False)),
                ('indifferent', models.BooleanField(default=False)),
                ('runs_from', models.BooleanField(default=False)),
            ],
        ),
    ]
