# Generated by Django 3.0 on 2019-12-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191204_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Approaches',
            new_name='approaches',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Chasing',
            new_name='chasing',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Climbing',
            new_name='climbing',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Eating',
            new_name='eating',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Kuks',
            new_name='foraging',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Moans',
            new_name='indifferent',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Quaas',
            new_name='kuks',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Running',
            new_name='moans',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Tail_flags',
            new_name='quaas',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Tail_twitches',
            new_name='running',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Foraging',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Indifferent',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Other_Activities',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Primary_Fur_Color',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Runs_from',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Shift',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Specific_Location',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
        ),
        migrations.AddField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('', '')], default='Adult', help_text='Age of Squirrel', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='fur_color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('', '')], default='Gray', help_text='Fur color of Squirrel', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='location',
            field=models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), ('', '')], default='Ground Plane', help_text='Location of Squirrel', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(blank=True, help_text='Other Activity', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='runs_from',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Sighting session', max_length=2),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, help_text='Specific location of Squirrel', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='squirrel_id',
            field=models.CharField(default=1, help_text="Unique Squirrel ID. If the ID already exist, sighting won't be added", max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_flags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.BooleanField(default=False),
        ),
    ]
