# Generated by Django 3.0 on 2019-12-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20191205_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('', '')], default='Adult', help_text='Age of Squirrel - Adult or Juvenile', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(help_text='Gives the date of sighting in YYYY-MM-DD format'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='fur_color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('', '')], default='Gray', help_text='Gives Fur color of the Squirrel', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='latitude',
            field=models.FloatField(help_text='Gives the Latitude of Sighting'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), ('', '')], default='Ground Plane', help_text='Location of Squirrel - on ground plane or above ground plane', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='longitude',
            field=models.FloatField(help_text='Gives the Longitude of Sighting'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Gives the time of sighting occurence - AM or PM', max_length=2),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, help_text='Additional information on Specific location of the Squirrel', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='squirrel_id',
            field=models.CharField(help_text='Gives Unique Squirrel ID. Sighting added only if the ID does not already exist', max_length=20, primary_key=True, serialize=False),
        ),
    ]
